#!/bin/sh

git config --global http.postBuffer 1024M

clone() {
    if ! git clone "git@github.com:$1.git" "$1"; then
        echo "$1 try 2..."
        if ! git clone "git@github.com:$1.git" "$1"; then
            echo "$1 try 3..."
            if ! git clone "git@github.com:$1.git" "$1"; then
                echo "WARNING: Failed to clone $1 after 3 tries."
            fi
        fi
    fi
}

clone "autopkg/48kRAM-recipes"
clone "autopkg/aanklewicz-recipes"
clone "autopkg/ahousseini-recipes"
clone "autopkg/andredb90-recipes"
clone "autopkg/andrewvalentine-recipes"
clone "autopkg/andrewzirkel-recipes"
clone "autopkg/apettinen-recipes"
clone "autopkg/apizz-recipes"
clone "autopkg/arubdesu-recipes"
clone "autopkg/aysiu-recipes"
clone "autopkg/bkerns-recipes"
clone "autopkg/blackthroat-recipes"
clone "autopkg/bnpl-recipes"
clone "autopkg/bochoven-recipes"
clone "autopkg/bradclare-recipes"
clone "autopkg/brianwells-recipes"
clone "autopkg/chalcahuite-recipes"
clone "autopkg/chefaustin-recipes"
clone "autopkg/chilcote-recipes"
clone "autopkg/clburlison-recipes"
clone "autopkg/crystalllized-recipes"
clone "autopkg/ctueck-recipes"
clone "autopkg/d33t5-recipes"
clone "autopkg/dankeller-recipes"
clone "autopkg/Darkomen78-recipes"
clone "autopkg/dataJAR-recipes"
clone "autopkg/dcoobs-recipes"
clone "autopkg/denmoff-recipes"
clone "autopkg/drewdiver-recipes"
clone "autopkg/eholtam-recipes"
clone "autopkg/erikng-recipes"
clone "autopkg/faumac-recipes"
clone "autopkg/filewave"
clone "autopkg/fishd72-recipes"
clone "autopkg/flammable-recipes"
clone "autopkg/flywire-recipes"
clone "autopkg/foigus-recipes"
clone "autopkg/ftiff-recipes"
clone "autopkg/gerardkok-recipes"
clone "autopkg/gilbertpalau-recipes"
clone "autopkg/giobbi-recipes"
clone "autopkg/gmarnin-recipes"
clone "autopkg/golbiga-recipes"
clone "autopkg/grahamgilbert-recipes"
clone "autopkg/grahampugh-recipes"
clone "autopkg/gregneagle-recipes"
clone "autopkg/groob-recipes"
clone "autopkg/haircut-recipes"
clone "autopkg/hansen-m-recipes"
clone "autopkg/hjuutilainen-recipes"
clone "autopkg/HobbitHardcase-recipes"
clone "autopkg/homebysix-recipes"
clone "autopkg/its-unibas-recipes"
clone "autopkg/jaharmi-recipes"
clone "autopkg/jannheider-recipes"
clone "autopkg/jazzace-recipes"
clone "autopkg/jbaker10-recipes"
clone "autopkg/jessepeterson-recipes"
clone "autopkg/jleggat-recipes"
clone "autopkg/jlehikoinen-recipes"
clone "autopkg/joncrain-recipes"
clone "autopkg/joshua-d-miller-recipes"
clone "autopkg/jpiel-recipes"
clone "autopkg/jps3-recipes"
clone "autopkg/jrsd-recipes"
clone "autopkg/jss-recipes"
clone "autopkg/justinrummel-recipes"
clone "autopkg/keeleysam-recipes"
clone "autopkg/kevinmcox-recipes"
clone "autopkg/killahquam-recipes"
clone "autopkg/kitzy-recipes"
clone "autopkg/lashomb-recipes"
clone "autopkg/lrz-recipes"
clone "autopkg/luisgiraldo-recipes"
clone "autopkg/macprince-recipes"
clone "autopkg/macvfx-recipes"
clone "autopkg/MichalMMac-recipes"
clone "autopkg/mikestechshop-recipes"
clone "autopkg/MLBZ521-recipes"
clone "autopkg/moofit-recipes"
clone "autopkg/morgrowe-recipes"
clone "autopkg/mosen-recipes"
clone "autopkg/munkireport-recipes"
clone "autopkg/n8felton-recipes"
clone "autopkg/natewalck-recipes"
clone "autopkg/nbalonso-recipes"
clone "autopkg/neilmartin83-recipes"
clone "autopkg/nmcspadden-recipes"
clone "autopkg/novaksam-recipes"
clone "autopkg/nstrauss-recipes"
clone "autopkg/nzmacgeek-recipes"
clone "autopkg/oliverweinm-recipes"
clone "autopkg/orbsmiv-recipes"
clone "autopkg/orchard-recipes"
clone "autopkg/patgmac-recipes"
clone "autopkg/paul-cossey-recipes"
clone "autopkg/peetinc-recipes"
clone "autopkg/peshay-recipes"
clone "autopkg/peterkelm-recipes"
clone "autopkg/precursorca-recipes"
clone "autopkg/primalcurve-recipes"
clone "autopkg/prochat-recipes"
clone "autopkg/psaintemarie-recipes"
clone "autopkg/rderewianko-recipes"
clone "autopkg/recipes"
clone "autopkg/rmanly-recipes"
clone "autopkg/robperc-recipes"
clone "autopkg/rtrouton-recipes"
clone "autopkg/rustymyers-recipes"
clone "autopkg/scriptingosx-recipes"
clone "autopkg/seansgm-recipes"
clone "autopkg/sebtomasi-recipes"
clone "autopkg/skoobasteeve-recipes"
clone "autopkg/smithjw-recipes"
clone "autopkg/swy-recipes"
clone "autopkg/tallfunnyjew-recipes"
clone "autopkg/tbridge-recipes"
clone "autopkg/Tecnico1931-recipes"
clone "autopkg/TekTekkers-recipes"
clone "autopkg/thenikola-recipes"
clone "autopkg/timsutton-recipes"
clone "autopkg/triti-recipes"
clone "autopkg/ucam-apple-support-recipes"
clone "autopkg/valdore86-recipes"
clone "autopkg/Vinrobot-recipes"
clone "autopkg/vmiller-recipes"
clone "autopkg/vmule-recipes"
clone "autopkg/wardsparadox-recipes"
clone "autopkg/watchmanmonitoring-recipes"
clone "autopkg/weswhet-recipes"
clone "autopkg/wholtz-recipes"
clone "autopkg/wycomco-recipes"
clone "autopkg/ygini-recipes"
clone "autopkg/Yohan460-recipes"
clone "autopkg/zachtarr-recipes"
clone "autopkg/zentral-recipes"
clone "autopkg/znerol-recipes"

echo "Done"
