target-version = "py38"
line-length = 100

[lint]
select = [
    "E",     # pycodestyle errors
    "F",     # pyflakes
    "I",     # isort
    "UP",    # pyupgrade
    "W",     # pycodestyle warnings
]

[lint.isort]
known-first-party = ["scripts"]
