name: build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    if: github.repository_owner == 'homebysix'
    runs-on: ubuntu-latest

    steps:
      - name: Clone this repository
        uses: actions/checkout@v2
        with:
          path: main

      - name: Clone AutoPkg org repos
        working-directory: main
        env:
          PA_TOKEN: ${{ secrets.PAT_SECRET }}
        run: .github/clone.sh
        shell: bash

      - name: Analyze recipes and rebuild site
        working-directory: main
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          ./build.py
          git add -A
          git commit -am "Analyze recipes and rebuild site" || true
