name: build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    if: github.repository_owner == 'homebysix'
    runs-on: ubuntu-latest

    steps:
      - name: Clone this repository
        uses: actions/checkout@v2
        with:
          path: main

      - name: Clone AutoPkg org repos
        env:
          PA_TOKEN: ${{ secrets.PAT_SECRET }}
        run: ./main/.github/clone.sh
        shell: bash

      - name: Analyze recipes and rebuild site
        working-directory: main
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          ./build.py
          git add docs/ || true
          git commit -m "Analyze recipes and rebuild site" docs/ || true
          git push --set-upstream origin main || true
